services:
  account-service:
    build:
      context:  ./account-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - Spring-microservice
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: hungnv
      SPRING_DATASOURCE_PASSWORD: 123abc
      SPRING_APPLICATION_NAME: department-service

networks:
  spring-microservice:
    driver: bridge
