spring.application.name=account-service
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/microservice
spring.datasource.username=root
spring.datasource.password=ninhdeptrai123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

app.auth.tokenSecret=acdb07d4cd4a32bcd146bf6a7a8d2f2c31c694a5aa228d071ca32f19c9b6291b6f7c70b536bd64326fcfe76a2a3790085e62bf75210f81976fe5a2e5e6274931

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
